### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Maxkie1** [lawrimon/PDA_SWE#92]
**User story:** [Link to the user story, if applicable]

**Description:** Implement a Redis database to store user preferences. This database will allow for efficient storage and retrieval of user preferences and will be used by multiple components of the system.

**Task List:**
- [x] Set up a Redis database instance to be used for preference storage
- [x] Design a schema for storing user preferences in Redis
- [x] Implement functions to store, retrieve, and update user preferences in the Redis database

**Acceptance Criteria:**
- [Criterion 1]
- [Criterion 2]
- [Criterion 3]
